# Generated by Django 4.2.6 on 2024-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcglobed_shop', '0002_rename_productids_productbuydetails_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuydetails',
            name='OrderDelivered',
            field=models.IntegerField(default=0),
        ),
    ]
